= Error messages and remedies for Kubernetes
:navtitle: Error messages and remedies
:description: This describes common error messages and their remedies when running the Keycloak Benchmark suite on Kubernetes.

{description}

[#keycloak-message-error-failed-to-obtain-jdbc-connection]
== Keycloak message `ERROR: Failed to obtain JDBC connection`

Context::
This error message can appear when running Keycloak with a relational database like PostgreSQL or CockroachDB.
+
Similar other error messages:
+
--
* "`Unable to acquire JDBC Connection`"
* "`Sorry, acquisition timeout!`"
--
+
This might happen during the startup and then the startup fails.
It might also happen during a load test when Keycloak creates new database connections.

Cause::
The database is either not started, or the number of database connections is exhausted in the current setup.

Remedy::
* Ensure that the database is running.
* Ensure that the database didn't restart, for example, due to an out-of-memory problem.
* Ensure that the number of DB connections in total doesn't exceed the maximum number of connections of the database.
See xref:customizing-deployment.adoc#KC_DB_POOL_INITIAL_SIZE[the Keycloak deployment configuration options `KC_DB_*`] for details.
* Ensure that Keycloak doesn't try to use more connections than configured as maximum numbers of connections.

Caution::
* Under high load, the number of database connections is usually the constraint of the system.
Having Keycloak running into a "`Sorry, acquisition timeout`" and returning an HTTP 5xx code to the caller is a sensible load shedding mechanism.
See xref:load-behavior.adoc[] for details.

[[retry-serializable]]
== Keycloak message `RETRY_SERIALIZABLE`

Full message::
org.postgresql.util.PSQLException, ERROR: restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE - failed preemptive refresh due to a conflict: intent on key /Table/137/... See: \https://www.cockroachlabs.com/docs/v22.1/transaction-retry-error-reference.html#retry_serializable

Context::
This error message can appear when running Keycloak with CockroachDB, both xref:storage/cockroach-single.adoc[single node] or xref:storage/cockroach-operator.adoc[multi node with the operator].
+
This might happen during the load test while Keycloak processes requests.

Cause::
Some transactions are not fully serializable as data has been modified in parallel transactions.

Effect::
The database rolls back the transaction and asks the caller to repeat the request.
Some users see error messages.

Remedy::
* Analyze the request/URL where this happens by looking at the log, and discuss this with engineers.
* Use the following SQL to determine the table which is causing the problems, which would by `137` in the example given above:
+
[source,sql]
----
SELECT DISTINCT ti.descriptor_name as table_name, us.table_id
  FROM  crdb_internal.index_usage_statistics us, crdb_internal.table_indexes ti
  WHERE us.table_id = ti.descriptor_id ORDER BY us.table_id ASC;
----

== Keycloak message `prepared transactions are disabled`

Full message::
org.postgresql.util.PSQLException: ERROR: prepared transactions are disabled.
Hint: Set max_prepared_transactions to a nonzero value.

Context::
This happens when the transaction manager or Quarkus handles more than one transaction in a request, and one of the transactions is handled by a PostgreSQL database.

Cause::
Once the transaction manager of Quarkus bundles two transactions, it sends a `PREPARE TRANSACTION` command to the database before sending the commit after all transactions have been prepared.
For this to work, the database needs to have the `max_prepared_transactions` parameter set.

Effect::
No transactions against the PostgreSQL database complete.

Remedy::
Pass the parameters `-c max_prepared_transactions=xxx` to the database.
For the containerized database in the Kubernetes setup, this has been configured in `link:{github-files}/provision/minikube/keycloak/templates/postgres/postgres-deployment.yaml[postgres-deployment.yaml]`.

== Keycloak message `ARJUNA012225: cannot access root of object store`

Full message::
ARJUNA012225: FileSystemStore::setupStore - cannot access root of object store: ObjectStore/ShadowNoFileLockStore/defaultStore/

Context::
This happens when the transaction manager or Quarkus handles more than one transaction in a request and attempts to locally persist the state of the transaction.

Cause::
The working directory of Keycloak is not writable in the Keycloak container, therefore writing the state fails.

Effect::
No transactions against any store participating in the JTA transaction complete, therefore Keycloak will not start.

Remedy::
Via the environment variable `QUARKUS_TRANSACTION_MANAGER_OBJECT_STORE_DIRECTORY` pass in a folder that is writable.
For the containerized Keycloak setup in the Kubernetes setup, this has been configured in `link:{github-files}provision/minikube/keycloak/templates/keycloak.yaml[keycloak.yaml]`.
